[project]
name = "disposable-email"
version = "0.1.0"
description = ""
authors = [
    {name = "AJ Anderson",email = "ajanderson1@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "polling2 (>=0.5.0,<0.6.0)",
    "rich (>=14.0.0,<15.0.0)",
    "python-guerrillamail (>=0.2.0,<0.3.0)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dev-dependencies]
ipykernel = "^6.29.5"
pandas = "^2.3.0"
pytest = "^8.4.1"

